using Infrastructure.Data;
using Module.Core.Entities;
using System.Collections.Generic;

namespace Module.Core.Data
{
    public class UpazilaSeedProvider : ISeedProvider<Upazila>
    {
        public int Order => 1;
        public IEnumerable<Upazila> GetSeeds()
        {
            return new List<Upazila>
            {
                new Upazila(1, 1, null, "Debidwar", "দেবিদ্বার"),
                new Upazila(2, 1, null, "Barura", "বরুড়া"),
                new Upazila(3, 1, null, "Brahmanpara", "ব্রাহ্মণপাড়া"),
                new Upazila(4, 1, null, "Chandina", "চান্দিনা"),
                new Upazila(5, 1, null, "Chauddagram", "চৌদ্দগ্রাম"),
                new Upazila(6, 1, null, "Daudkandi", "দাউদকান্দি"),
                new Upazila(7, 1, null, "Homna", "হোমনা"),
                new Upazila(8, 1, null, "Laksam", "লাকসাম"),
                new Upazila(9, 1, null, "Muradnagar", "মুরাদনগর"),
                new Upazila(10, 1, null, "Nangalkot", "নাঙ্গলকোট"),
                new Upazila(11, 1, null, "Comilla Sadar", "কুমিল্লা সদর"),
                new Upazila(12, 1, null, "Meghna", "মেঘনা"),
                new Upazila(13, 1, null, "Monohargonj", "মনোহরগঞ্জ"),
                new Upazila(14, 1, null, "Sadarsouth", "সদর দক্ষিণ"),
                new Upazila(15, 1, null, "Titas", "তিতাস"),
                new Upazila(16, 1, null, "Burichang", "বুড়িচং"),
                new Upazila(17, 1, null, "Lalmai", "লালমাই"),
                new Upazila(18, 2, null, "Chhagalnaiya", "ছাগলনাইয়া"),
                new Upazila(19, 2, null, "Feni Sadar", "ফেনী সদর"),
                new Upazila(20, 2, null, "Sonagazi", "সোনাগাজী"),
                new Upazila(21, 2, null, "Fulgazi", "ফুলগাজী"),
                new Upazila(22, 2, null, "Parshuram", "পরশুরাম"),
                new Upazila(23, 2, null, "Daganbhuiyan", "দাগনভূঞা"),
                new Upazila(24, 3, null, "Brahmanbaria Sadar", "ব্রাহ্মণবাড়িয়া সদর"),
                new Upazila(25, 3, null, "Kasba", "কসবা"),
                new Upazila(26, 3, null, "Nasirnagar", "নাসিরনগর"),
                new Upazila(27, 3, null, "Sarail", "সরাইল"),
                new Upazila(28, 3, null, "Ashuganj", "আশুগঞ্জ"),
                new Upazila(29, 3, null, "Akhaura", "আখাউড়া"),
                new Upazila(30, 3, null, "Nabinagar", "নবীনগর"),
                new Upazila(31, 3, null, "Bancharampur", "বাঞ্ছারামপুর"),
                new Upazila(32, 3, null, "Bijoynagar", "বিজয়নগর"),
                new Upazila(33, 4, null, "Rangamati Sadar", "রাঙ্গামাটি সদর"),
                new Upazila(34, 4, null, "Kaptai", "কাপ্তাই"),
                new Upazila(35, 4, null, "Kawkhali", "কাউখালী"),
                new Upazila(36, 4, null, "Baghaichari", "বাঘাইছড়ি"),
                new Upazila(37, 4, null, "Barkal", "বরকল"),
                new Upazila(38, 4, null, "Langadu", "লংগদু"),
                new Upazila(39, 4, null, "Rajasthali", "রাজস্থলী"),
                new Upazila(40, 4, null, "Belaichari", "বিলাইছড়ি"),
                new Upazila(41, 4, null, "Juraichari", "জুরাছড়ি"),
                new Upazila(42, 4, null, "Naniarchar", "নানিয়ারচর"),
                new Upazila(43, 5, null, "Noakhali Sadar", "নোয়াখালী সদর"),
                new Upazila(44, 5, null, "Companiganj", "কোম্পানীগঞ্জ"),
                new Upazila(45, 5, null, "Begumganj", "বেগমগঞ্জ"),
                new Upazila(46, 5, null, "Hatia", "হাতিয়া"),
                new Upazila(47, 5, null, "Subarnachar", "সুবর্ণচর"),
                new Upazila(48, 5, null, "Kabirhat", "কবিরহাট"),
                new Upazila(49, 5, null, "Senbug", "সেনবাগ"),
                new Upazila(50, 5, null, "Chatkhil", "চাটখিল"),
                new Upazila(51, 5, null, "Sonaimori", "সোনাইমুড়ী"),
                new Upazila(52, 6, null, "Haimchar", "হাইমচর"),
                new Upazila(53, 6, null, "Kachua", "কচুয়া"),
                new Upazila(54, 6, null, "Shahrasti", "শাহরাস্তি"),
                new Upazila(55, 6, null, "Chandpur Sadar", "চাঁদপুর সদর"),
                new Upazila(56, 6, null, "Matlab South", "মতলব দক্ষিণ"),
                new Upazila(57, 6, null, "Hajiganj", "হাজীগঞ্জ"),
                new Upazila(58, 6, null, "Matlab North", "মতলব উত্তর"),
                new Upazila(59, 6, null, "Faridgonj", "ফরিদগঞ্জ"),
                new Upazila(60, 7, null, "Lakshmipur Sadar", "লক্ষ্মীপুর সদর"),
                new Upazila(61, 7, null, "Kamalnagar", "কমলনগর"),
                new Upazila(62, 7, null, "Raipur", "রায়পুর"),
                new Upazila(63, 7, null, "Ramgati", "রামগতি"),
                new Upazila(64, 7, null, "Ramganj", "রামগঞ্জ"),
                new Upazila(65, 8, null, "Rangunia", "রাঙ্গুনিয়া"),
                new Upazila(66, 8, null, "Sitakunda", "সীতাকুন্ড"),
                new Upazila(67, 8, null, "Mirsharai", "মীরসরাই"),
                new Upazila(68, 8, null, "Patiya", "পটিয়া"),
                new Upazila(69, 8, null, "Sandwip", "সন্দ্বীপ"),
                new Upazila(70, 8, null, "Banshkhali", "বাঁশখালী"),
                new Upazila(71, 8, null, "Boalkhali", "বোয়ালখালী"),
                new Upazila(72, 8, null, "Anwara", "আনোয়ারা"),
                new Upazila(73, 8, null, "Chandanaish", "চন্দনাইশ"),
                new Upazila(74, 8, null, "Satkania", "সাতকানিয়া"),
                new Upazila(75, 8, null, "Lohagara", "লোহাগাড়া"),
                new Upazila(76, 8, null, "Hathazari", "হাটহাজারী"),
                new Upazila(77, 8, null, "Fatikchhari", "ফটিকছড়ি"),
                new Upazila(78, 8, null, "Raozan", "রাউজান"),
                new Upazila(79, 8, null, "Karnafuli", "কর্ণফুলী"),
                new Upazila(80, 9, null, "Coxsbazar Sadar", "কক্সবাজার সদর"),
                new Upazila(81, 9, null, "Chakaria", "চকরিয়া"),
                new Upazila(82, 9, null, "Kutubdia", "কুতুবদিয়া"),
                new Upazila(83, 9, null, "Ukhiya", "উখিয়া"),
                new Upazila(84, 9, null, "Moheshkhali", "মহেশখালী"),
                new Upazila(85, 9, null, "Pekua", "পেকুয়া"),
                new Upazila(86, 9, null, "Ramu", "রামু"),
                new Upazila(87, 9, null, "Teknaf", "টেকনাফ"),
                new Upazila(88, 10, null, "Khagrachhari Sadar", "খাগড়াছড়ি সদর"),
                new Upazila(89, 10, null, "Dighinala", "দিঘীনালা"),
                new Upazila(90, 10, null, "Panchari", "পানছড়ি"),
                new Upazila(91, 10, null, "Laxmichhari", "লক্ষীছড়ি"),
                new Upazila(92, 10, null, "Mohalchari", "মহালছড়ি"),
                new Upazila(93, 10, null, "Manikchari", "মানিকছড়ি"),
                new Upazila(94, 10, null, "Ramgarh", "রামগড়"),
                new Upazila(95, 10, null, "Matiranga", "মাটিরাঙ্গা"),
                new Upazila(96, 10, null, "Guimara", "গুইমারা"),
                new Upazila(97, 11, null, "Bandarban Sadar", "বান্দরবান সদর"),
                new Upazila(98, 11, null, "Alikadam", "আলীকদম"),
                new Upazila(99, 11, null, "Naikhongchhari", "নাইক্ষ্যংছড়ি"),
                new Upazila(100, 11, null, "Rowangchhari", "রোয়াংছড়ি"),
                new Upazila(101, 11, null, "Lama", "লামা"),
                new Upazila(102, 11, null, "Ruma", "রুমা"),
                new Upazila(103, 11, null, "Thanchi", "থানচি"),
                new Upazila(104, 12, null, "Belkuchi", "বেলকুচি"),
                new Upazila(105, 12, null, "Chauhali", "চৌহালি"),
                new Upazila(106, 12, null, "Kamarkhand", "কামারখন্দ"),
                new Upazila(107, 12, null, "Kazipur", "কাজীপুর"),
                new Upazila(108, 12, null, "Raigonj", "রায়গঞ্জ"),
                new Upazila(109, 12, null, "Shahjadpur", "শাহজাদপুর"),
                new Upazila(110, 12, null, "Sirajganj Sadar", "সিরাজগঞ্জ সদর"),
                new Upazila(111, 12, null, "Tarash", "তাড়াশ"),
                new Upazila(112, 12, null, "Ullapara", "উল্লাপাড়া"),
                new Upazila(113, 13, null, "Sujanagar", "সুজানগর"),
                new Upazila(114, 13, null, "Ishurdi", "ঈশ্বরদী"),
                new Upazila(115, 13, null, "Bhangura", "ভাঙ্গুড়া"),
                new Upazila(116, 13, null, "Pabna Sadar", "পাবনা সদর"),
                new Upazila(117, 13, null, "Bera", "বেড়া"),
                new Upazila(118, 13, null, "Atghoria", "আটঘরিয়া"),
                new Upazila(119, 13, null, "Chatmohar", "চাটমোহর"),
                new Upazila(120, 13, null, "Santhia", "সাঁথিয়া"),
                new Upazila(121, 13, null, "Faridpur", "ফরিদপুর"),
                new Upazila(122, 14, null, "Kahaloo", "কাহালু"),
                new Upazila(123, 14, null, "Bogra Sadar", "বগুড়া সদর"),
                new Upazila(124, 14, null, "Shariakandi", "সারিয়াকান্দি"),
                new Upazila(125, 14, null, "Shajahanpur", "শাজাহানপুর"),
                new Upazila(126, 14, null, "Dupchanchia", "দুপচাচিঁয়া"),
                new Upazila(127, 14, null, "Adamdighi", "আদমদিঘি"),
                new Upazila(128, 14, null, "Nondigram", "নন্দিগ্রাম"),
                new Upazila(129, 14, null, "Sonatala", "সোনাতলা"),
                new Upazila(130, 14, null, "Dhunot", "ধুনট"),
                new Upazila(131, 14, null, "Gabtali", "গাবতলী"),
                new Upazila(132, 14, null, "Sherpur", "শেরপুর"),
                new Upazila(133, 14, null, "Shibganj", "শিবগঞ্জ"),
                new Upazila(134, 15, null, "Paba", "পবা"),
                new Upazila(135, 15, null, "Durgapur", "দুর্গাপুর"),
                new Upazila(136, 15, null, "Mohonpur", "মোহনপুর"),
                new Upazila(137, 15, null, "Charghat", "চারঘাট"),
                new Upazila(138, 15, null, "Puthia", "পুঠিয়া"),
                new Upazila(139, 15, null, "Bagha", "বাঘা"),
                new Upazila(140, 15, null, "Godagari", "গোদাগাড়ী"),
                new Upazila(141, 15, null, "Tanore", "তানোর"),
                new Upazila(142, 15, null, "Bagmara", "বাগমারা"),
                new Upazila(143, 16, null, "Natore Sadar", "নাটোর সদর"),
                new Upazila(144, 16, null, "Singra", "সিংড়া"),
                new Upazila(145, 16, null, "Baraigram", "বড়াইগ্রাম"),
                new Upazila(146, 16, null, "Bagatipara", "বাগাতিপাড়া"),
                new Upazila(147, 16, null, "Lalpur", "লালপুর"),
                new Upazila(148, 16, null, "Gurudaspur", "গুরুদাসপুর"),
                new Upazila(149, 16, null, "Naldanga", "নলডাঙ্গা"),
                new Upazila(150, 17, null, "Akkelpur", "আক্কেলপুর"),
                new Upazila(151, 17, null, "Kalai", "কালাই"),
                new Upazila(152, 17, null, "Khetlal", "ক্ষেতলাল"),
                new Upazila(153, 17, null, "Panchbibi", "পাঁচবিবি"),
                new Upazila(154, 17, null, "Joypurhat Sadar", "জয়পুরহাট সদর"),
                new Upazila(155, 18, null, "Chapainawabganj Sadar", "চাঁপাইনবাবগঞ্জ সদর"),
                new Upazila(156, 18, null, "Gomostapur", "গোমস্তাপুর"),
                new Upazila(157, 18, null, "Nachol", "নাচোল"),
                new Upazila(158, 18, null, "Bholahat", "ভোলাহাট"),
                new Upazila(159, 18, null, "Shibganj", "শিবগঞ্জ"),
                new Upazila(160, 19, null, "Mohadevpur", "মহাদেবপুর"),
                new Upazila(161, 19, null, "Badalgachi", "বদলগাছী"),
                new Upazila(162, 19, null, "Patnitala", "পত্নিতলা"),
                new Upazila(163, 19, null, "Dhamoirhat", "ধামইরহাট"),
                new Upazila(164, 19, null, "Niamatpur", "নিয়ামতপুর"),
                new Upazila(165, 19, null, "Manda", "মান্দা"),
                new Upazila(166, 19, null, "Atrai", "আত্রাই"),
                new Upazila(167, 19, null, "Raninagar", "রাণীনগর"),
                new Upazila(168, 19, null, "Naogaon Sadar", "নওগাঁ সদর"),
                new Upazila(169, 19, null, "Porsha", "পোরশা"),
                new Upazila(170, 19, null, "Sapahar", "সাপাহার"),
                new Upazila(171, 20, null, "Manirampur", "মণিরামপুর"),
                new Upazila(172, 20, null, "Abhaynagar", "অভয়নগর"),
                new Upazila(173, 20, null, "Bagherpara", "বাঘারপাড়া"),
                new Upazila(174, 20, null, "Chougachha", "চৌগাছা"),
                new Upazila(175, 20, null, "Jhikargacha", "ঝিকরগাছা"),
                new Upazila(176, 20, null, "Keshabpur", "কেশবপুর"),
                new Upazila(177, 20, null, "Jessore Sadar", "যশোর সদর"),
                new Upazila(178, 20, null, "Sharsha", "শার্শা"),
                new Upazila(179, 21, null, "Assasuni", "আশাশুনি"),
                new Upazila(180, 21, null, "Debhata", "দেবহাটা"),
                new Upazila(181, 21, null, "Kalaroa", "কলারোয়া"),
                new Upazila(182, 21, null, "Satkhira Sadar", "সাতক্ষীরা সদর"),
                new Upazila(183, 21, null, "Shyamnagar", "শ্যামনগর"),
                new Upazila(184, 21, null, "Tala", "তালা"),
                new Upazila(185, 21, null, "Kaliganj", "কালিগঞ্জ"),
                new Upazila(186, 22, null, "Mujibnagar", "মুজিবনগর"),
                new Upazila(187, 22, null, "Meherpur Sadar", "মেহেরপুর সদর"),
                new Upazila(188, 22, null, "Gangni", "গাংনী"),
                new Upazila(189, 23, null, "Narail Sadar", "নড়াইল সদর"),
                new Upazila(190, 23, null, "Lohagara", "লোহাগড়া"),
                new Upazila(191, 23, null, "Kalia", "কালিয়া"),
                new Upazila(192, 24, null, "Chuadanga Sadar", "চুয়াডাঙ্গা সদর"),
                new Upazila(193, 24, null, "Alamdanga", "আলমডাঙ্গা"),
                new Upazila(194, 24, null, "Damurhuda", "দামুড়হুদা"),
                new Upazila(195, 24, null, "Jibannagar", "জীবননগর"),
                new Upazila(196, 25, null, "Kushtia Sadar", "কুষ্টিয়া সদর"),
                new Upazila(197, 25, null, "Kumarkhali", "কুমারখালী"),
                new Upazila(198, 25, null, "Khoksa", "খোকসা"),
                new Upazila(199, 25, null, "Mirpur", "মিরপুর"),
                new Upazila(200, 25, null, "Daulatpur", "দৌলতপুর"),
                new Upazila(201, 25, null, "Bheramara", "ভেড়ামারা"),
                new Upazila(202, 26, null, "Shalikha", "শালিখা"),
                new Upazila(203, 26, null, "Sreepur", "শ্রীপুর"),
                new Upazila(204, 26, null, "Magura Sadar", "মাগুরা সদর"),
                new Upazila(205, 26, null, "Mohammadpur", "মহম্মদপুর"),
                new Upazila(206, 27, null, "Paikgasa", "পাইকগাছা"),
                new Upazila(207, 27, null, "Fultola", "ফুলতলা"),
                new Upazila(208, 27, null, "Digholia", "দিঘলিয়া"),
                new Upazila(209, 27, null, "Rupsha", "রূপসা"),
                new Upazila(210, 27, null, "Terokhada", "তেরখাদা"),
                new Upazila(211, 27, null, "Dumuria", "ডুমুরিয়া"),
                new Upazila(212, 27, null, "Botiaghata", "বটিয়াঘাটা"),
                new Upazila(213, 27, null, "Dakop", "দাকোপ"),
                new Upazila(214, 27, null, "Koyra", "কয়রা"),
                new Upazila(215, 28, null, "Fakirhat", "ফকিরহাট"),
                new Upazila(216, 28, null, "Bagerhat Sadar", "বাগেরহাট সদর"),
                new Upazila(217, 28, null, "Mollahat", "মোল্লাহাট"),
                new Upazila(218, 28, null, "Sarankhola", "শরণখোলা"),
                new Upazila(219, 28, null, "Rampal", "রামপাল"),
                new Upazila(220, 28, null, "Morrelganj", "মোড়েলগঞ্জ"),
                new Upazila(221, 28, null, "Kachua", "কচুয়া"),
                new Upazila(222, 28, null, "Mongla", "মোংলা"),
                new Upazila(223, 28, null, "Chitalmari", "চিতলমারী"),
                new Upazila(224, 29, null, "Jhenaidah Sadar", "ঝিনাইদহ সদর"),
                new Upazila(225, 29, null, "Shailkupa", "শৈলকুপা"),
                new Upazila(226, 29, null, "Harinakundu", "হরিণাকুন্ডু"),
                new Upazila(227, 29, null, "Kaliganj", "কালীগঞ্জ"),
                new Upazila(228, 29, null, "Kotchandpur", "কোটচাঁদপুর"),
                new Upazila(229, 29, null, "Moheshpur", "মহেশপুর"),
                new Upazila(230, 30, null, "Jhalakathi Sadar", "ঝালকাঠি সদর"),
                new Upazila(231, 30, null, "Kathalia", "কাঠালিয়া"),
                new Upazila(232, 30, null, "Nalchity", "নলছিটি"),
                new Upazila(233, 30, null, "Rajapur", "রাজাপুর"),
                new Upazila(234, 31, null, "Bauphal", "বাউফল"),
                new Upazila(235, 31, null, "Patuakhali Sadar", "পটুয়াখালী সদর"),
                new Upazila(236, 31, null, "Dumki", "দুমকি"),
                new Upazila(237, 31, null, "Dashmina", "দশমিনা"),
                new Upazila(238, 31, null, "Kalapara", "কলাপাড়া"),
                new Upazila(239, 31, null, "Mirzaganj", "মির্জাগঞ্জ"),
                new Upazila(240, 31, null, "Galachipa", "গলাচিপা"),
                new Upazila(241, 31, null, "Rangabali", "রাঙ্গাবালী"),
                new Upazila(242, 32, null, "Pirojpur Sadar", "পিরোজপুর সদর"),
                new Upazila(243, 32, null, "Nazirpur", "নাজিরপুর"),
                new Upazila(244, 32, null, "Kawkhali", "কাউখালী"),
                new Upazila(245, 32, null, "Zianagar", "জিয়ানগর"),
                new Upazila(246, 32, null, "Bhandaria", "ভান্ডারিয়া"),
                new Upazila(247, 32, null, "Mathbaria", "মঠবাড়ীয়া"),
                new Upazila(248, 32, null, "Nesarabad", "নেছারাবাদ"),
                new Upazila(249, 33, null, "Barisal Sadar", "বরিশাল সদর"),
                new Upazila(250, 33, null, "Bakerganj", "বাকেরগঞ্জ"),
                new Upazila(251, 33, null, "Babuganj", "বাবুগঞ্জ"),
                new Upazila(252, 33, null, "Wazirpur", "উজিরপুর"),
                new Upazila(253, 33, null, "Banaripara", "বানারীপাড়া"),
                new Upazila(254, 33, null, "Gournadi", "গৌরনদী"),
                new Upazila(255, 33, null, "Agailjhara", "আগৈলঝাড়া"),
                new Upazila(256, 33, null, "Mehendiganj", "মেহেন্দিগঞ্জ"),
                new Upazila(257, 33, null, "Muladi", "মুলাদী"),
                new Upazila(258, 33, null, "Hizla", "হিজলা"),
                new Upazila(259, 34, null, "Bhola Sadar", "ভোলা সদর"),
                new Upazila(260, 34, null, "Borhan Sddin", "বোরহান উদ্দিন"),
                new Upazila(261, 34, null, "Charfesson", "চরফ্যাশন"),
                new Upazila(262, 34, null, "Doulatkhan", "দৌলতখান"),
                new Upazila(263, 34, null, "Monpura", "মনপুরা"),
                new Upazila(264, 34, null, "Tazumuddin", "তজুমদ্দিন"),
                new Upazila(265, 34, null, "Lalmohan", "লালমোহন"),
                new Upazila(266, 35, null, "Amtali", "আমতলী"),
                new Upazila(267, 35, null, "Barguna Sadar", "বরগুনা সদর"),
                new Upazila(268, 35, null, "Betagi", "বেতাগী"),
                new Upazila(269, 35, null, "Bamna", "বামনা"),
                new Upazila(270, 35, null, "Pathorghata", "পাথরঘাটা"),
                new Upazila(271, 35, null, "Taltali", "তালতলি"),
                new Upazila(272, 36, null, "Balaganj", "বালাগঞ্জ"),
                new Upazila(273, 36, null, "Beanibazar", "বিয়ানীবাজার"),
                new Upazila(274, 36, null, "Bishwanath", "বিশ্বনাথ"),
                new Upazila(275, 36, null, "Companiganj", "কোম্পানীগঞ্জ"),
                new Upazila(276, 36, null, "Fenchuganj", "ফেঞ্চুগঞ্জ"),
                new Upazila(277, 36, null, "Golapganj", "গোলাপগঞ্জ"),
                new Upazila(278, 36, null, "Gowainghat", "গোয়াইনঘাট"),
                new Upazila(279, 36, null, "Jaintiapur", "জৈন্তাপুর"),
                new Upazila(280, 36, null, "Kanaighat", "কানাইঘাট"),
                new Upazila(281, 36, null, "Sylhet Sadar", "সিলেট সদর"),
                new Upazila(282, 36, null, "Zakiganj", "জকিগঞ্জ"),
                new Upazila(283, 36, null, "Dakshinsurma", "দক্ষিণ সুরমা"),
                new Upazila(284, 36, null, "Osmaninagar", "ওসমানী নগর"),
                new Upazila(285, 37, null, "Barlekha", "বড়লেখা"),
                new Upazila(286, 37, null, "Kamolganj", "কমলগঞ্জ"),
                new Upazila(287, 37, null, "Kulaura", "কুলাউড়া"),
                new Upazila(288, 37, null, "Moulvibazar Sadar", "মৌলভীবাজার সদর"),
                new Upazila(289, 37, null, "Rajnagar", "রাজনগর"),
                new Upazila(290, 37, null, "Sreemangal", "শ্রীমঙ্গল"),
                new Upazila(291, 37, null, "Juri", "জুড়ী"),
                new Upazila(292, 38, null, "Nabiganj", "নবীগঞ্জ"),
                new Upazila(293, 38, null, "Bahubal", "বাহুবল"),
                new Upazila(294, 38, null, "Ajmiriganj", "আজমিরীগঞ্জ"),
                new Upazila(295, 38, null, "Baniachong", "বানিয়াচং"),
                new Upazila(296, 38, null, "Lakhai", "লাখাই"),
                new Upazila(297, 38, null, "Chunarughat", "চুনারুঘাট"),
                new Upazila(298, 38, null, "Habiganj Sadar", "হবিগঞ্জ সদর"),
                new Upazila(299, 38, null, "Madhabpur", "মাধবপুর"),
                new Upazila(300, 39, null, "Sunamganj Sadar", "সুনামগঞ্জ সদর"),
                new Upazila(301, 39, null, "South Sunamganj", "দক্ষিণ সুনামগঞ্জ"),
                new Upazila(302, 39, null, "Bishwambarpur", "বিশ্বম্ভরপুর"),
                new Upazila(303, 39, null, "Chhatak", "ছাতক"),
                new Upazila(304, 39, null, "Jagannathpur", "জগন্নাথপুর"),
                new Upazila(305, 39, null, "Dowarabazar", "দোয়ারাবাজার"),
                new Upazila(306, 39, null, "Tahirpur", "তাহিরপুর"),
                new Upazila(307, 39, null, "Dharmapasha", "ধর্মপাশা"),
                new Upazila(308, 39, null, "Jamalganj", "জামালগঞ্জ"),
                new Upazila(309, 39, null, "Shalla", "শাল্লা"),
                new Upazila(310, 39, null, "Derai", "দিরাই"),
                new Upazila(311, 40, null, "Belabo", "বেলাবো"),
                new Upazila(312, 40, null, "Monohardi", "মনোহরদী"),
                new Upazila(313, 40, null, "Narsingdi Sadar", "নরসিংদী সদর"),
                new Upazila(314, 40, null, "Palash", "পলাশ"),
                new Upazila(315, 40, null, "Raipura", "রায়পুরা"),
                new Upazila(316, 40, null, "Shibpur", "শিবপুর"),
                new Upazila(317, 41, null, "Kaliganj", "কালীগঞ্জ"),
                new Upazila(318, 41, null, "Kaliakair", "কালিয়াকৈর"),
                new Upazila(319, 41, null, "Kapasia", "কাপাসিয়া"),
                new Upazila(320, 41, null, "Gazipur Sadar", "গাজীপুর সদর"),
                new Upazila(321, 41, null, "Sreepur", "শ্রীপুর"),
                new Upazila(322, 42, null, "Shariatpur Sadar", "শরিয়তপুর সদর"),
                new Upazila(323, 42, null, "Naria", "নড়িয়া"),
                new Upazila(324, 42, null, "Zajira", "জাজিরা"),
                new Upazila(325, 42, null, "Gosairhat", "গোসাইরহাট"),
                new Upazila(326, 42, null, "Bhedarganj", "ভেদরগঞ্জ"),
                new Upazila(327, 42, null, "Damudya", "ডামুড্যা"),
                new Upazila(328, 43, null, "Araihazar", "আড়াইহাজার"),
                new Upazila(329, 43, null, "Bandar", "বন্দর"),
                new Upazila(330, 43, null, "Narayanganj Sadar", "নারায়নগঞ্জ সদর"),
                new Upazila(331, 43, null, "Rupganj", "রূপগঞ্জ"),
                new Upazila(332, 43, null, "Sonargaon", "সোনারগাঁ"),
                new Upazila(333, 44, null, "Basail", "বাসাইল"),
                new Upazila(334, 44, null, "Bhuapur", "ভুয়াপুর"),
                new Upazila(335, 44, null, "Delduar", "দেলদুয়ার"),
                new Upazila(336, 44, null, "Ghatail", "ঘাটাইল"),
                new Upazila(337, 44, null, "Gopalpur", "গোপালপুর"),
                new Upazila(338, 44, null, "Madhupur", "মধুপুর"),
                new Upazila(339, 44, null, "Mirzapur", "মির্জাপুর"),
                new Upazila(340, 44, null, "Nagarpur", "নাগরপুর"),
                new Upazila(341, 44, null, "Sakhipur", "সখিপুর"),
                new Upazila(342, 44, null, "Tangail Sadar", "টাঙ্গাইল সদর"),
                new Upazila(343, 44, null, "Kalihati", "কালিহাতী"),
                new Upazila(344, 44, null, "Dhanbari", "ধনবাড়ী"),
                new Upazila(345, 45, null, "Itna", "ইটনা"),
                new Upazila(346, 45, null, "Katiadi", "কটিয়াদী"),
                new Upazila(347, 45, null, "Bhairab", "ভৈরব"),
                new Upazila(348, 45, null, "Tarail", "তাড়াইল"),
                new Upazila(349, 45, null, "Hossainpur", "হোসেনপুর"),
                new Upazila(350, 45, null, "Pakundia", "পাকুন্দিয়া"),
                new Upazila(351, 45, null, "Kuliarchar", "কুলিয়ারচর"),
                new Upazila(352, 45, null, "Kishoreganj Sadar", "কিশোরগঞ্জ সদর"),
                new Upazila(353, 45, null, "Karimgonj", "করিমগঞ্জ"),
                new Upazila(354, 45, null, "Bajitpur", "বাজিতপুর"),
                new Upazila(355, 45, null, "Austagram", "অষ্টগ্রাম"),
                new Upazila(356, 45, null, "Mithamoin", "মিঠামইন"),
                new Upazila(357, 45, null, "Nikli", "নিকলী"),
                new Upazila(358, 46, null, "Harirampur", "হরিরামপুর"),
                new Upazila(359, 46, null, "Saturia", "সাটুরিয়া"),
                new Upazila(360, 46, null, "Manikganj Sadar", "মানিকগঞ্জ সদর"),
                new Upazila(361, 46, null, "Gior", "ঘিওর"),
                new Upazila(362, 46, null, "Shibaloy", "শিবালয়"),
                new Upazila(363, 46, null, "Doulatpur", "দৌলতপুর"),
                new Upazila(364, 46, null, "Singiar", "সিংগাইর"),
                new Upazila(365, 47, null, "Savar", "সাভার"),
                new Upazila(366, 47, null, "Dhamrai", "ধামরাই"),
                new Upazila(367, 47, null, "Keraniganj", "কেরাণীগঞ্জ"),
                new Upazila(368, 47, null, "Nawabganj", "নবাবগঞ্জ"),
                new Upazila(369, 47, null, "Dohar", "দোহার"),
                new Upazila(370, 48, null, "Munshiganj Sadar", "মুন্সিগঞ্জ সদর"),
                new Upazila(371, 48, null, "Sreenagar", "শ্রীনগর"),
                new Upazila(372, 48, null, "Sirajdikhan", "সিরাজদিখান"),
                new Upazila(373, 48, null, "Louhajanj", "লৌহজং"),
                new Upazila(374, 48, null, "Gajaria", "গজারিয়া"),
                new Upazila(375, 48, null, "Tongibari", "টংগীবাড়ি"),
                new Upazila(376, 49, null, "Rajbari Sadar", "রাজবাড়ী সদর"),
                new Upazila(377, 49, null, "Goalanda", "গোয়ালন্দ"),
                new Upazila(378, 49, null, "Pangsa", "পাংশা"),
                new Upazila(379, 49, null, "Baliakandi", "বালিয়াকান্দি"),
                new Upazila(380, 49, null, "Kalukhali", "কালুখালী"),
                new Upazila(381, 50, null, "Madaripur Sadar", "মাদারীপুর সদর"),
                new Upazila(382, 50, null, "Shibchar", "শিবচর"),
                new Upazila(383, 50, null, "Kalkini", "কালকিনি"),
                new Upazila(384, 50, null, "Rajoir", "রাজৈর"),
                new Upazila(385, 51, null, "Gopalganj Sadar", "গোপালগঞ্জ সদর"),
                new Upazila(386, 51, null, "Kashiani", "কাশিয়ানী"),
                new Upazila(387, 51, null, "Tungipara", "টুংগীপাড়া"),
                new Upazila(388, 51, null, "Kotalipara", "কোটালীপাড়া"),
                new Upazila(389, 51, null, "Muksudpur", "মুকসুদপুর"),
                new Upazila(390, 52, null, "Faridpur Sadar", "ফরিদপুর সদর"),
                new Upazila(391, 52, null, "Alfadanga", "আলফাডাঙ্গা"),
                new Upazila(392, 52, null, "Boalmari", "বোয়ালমারী"),
                new Upazila(393, 52, null, "Sadarpur", "সদরপুর"),
                new Upazila(394, 52, null, "Nagarkanda", "নগরকান্দা"),
                new Upazila(395, 52, null, "Bhanga", "ভাঙ্গা"),
                new Upazila(396, 52, null, "Charbhadrasan", "চরভদ্রাসন"),
                new Upazila(397, 52, null, "Madhukhali", "মধুখালী"),
                new Upazila(398, 52, null, "Saltha", "সালথা"),
                new Upazila(399, 53, null, "Panchagarh Sadar", "পঞ্চগড় সদর"),
                new Upazila(400, 53, null, "Debiganj", "দেবীগঞ্জ"),
                new Upazila(401, 53, null, "Boda", "বোদা"),
                new Upazila(402, 53, null, "Atwari", "আটোয়ারী"),
                new Upazila(403, 53, null, "Tetulia", "তেতুলিয়া"),
                new Upazila(404, 54, null, "Nawabganj", "নবাবগঞ্জ"),
                new Upazila(405, 54, null, "Birganj", "বীরগঞ্জ"),
                new Upazila(406, 54, null, "Ghoraghat", "ঘোড়াঘাট"),
                new Upazila(407, 54, null, "Birampur", "বিরামপুর"),
                new Upazila(408, 54, null, "Parbatipur", "পার্বতীপুর"),
                new Upazila(409, 54, null, "Bochaganj", "বোচাগঞ্জ"),
                new Upazila(410, 54, null, "Kaharol", "কাহারোল"),
                new Upazila(411, 54, null, "Fulbari", "ফুলবাড়ী"),
                new Upazila(412, 54, null, "Dinajpur Sadar", "দিনাজপুর সদর"),
                new Upazila(413, 54, null, "Hakimpur", "হাকিমপুর"),
                new Upazila(414, 54, null, "Khansama", "খানসামা"),
                new Upazila(415, 54, null, "Birol", "বিরল"),
                new Upazila(416, 54, null, "Chirirbandar", "চিরিরবন্দর"),
                new Upazila(417, 55, null, "Lalmonirhat Sadar", "লালমনিরহাট সদর"),
                new Upazila(418, 55, null, "Kaliganj", "কালীগঞ্জ"),
                new Upazila(419, 55, null, "Hatibandha", "হাতীবান্ধা"),
                new Upazila(420, 55, null, "Patgram", "পাটগ্রাম"),
                new Upazila(421, 55, null, "Aditmari", "আদিতমারী"),
                new Upazila(422, 56, null, "Syedpur", "সৈয়দপুর"),
                new Upazila(423, 56, null, "Domar", "ডোমার"),
                new Upazila(424, 56, null, "Dimla", "ডিমলা"),
                new Upazila(425, 56, null, "Jaldhaka", "জলঢাকা"),
                new Upazila(426, 56, null, "Kishorganj", "কিশোরগঞ্জ"),
                new Upazila(427, 56, null, "Nilphamari Sadar", "নীলফামারী সদর"),
                new Upazila(428, 57, null, "Sadullapur", "সাদুল্লাপুর"),
                new Upazila(429, 57, null, "Gaibandha Sadar", "গাইবান্ধা সদর"),
                new Upazila(430, 57, null, "Palashbari", "পলাশবাড়ী"),
                new Upazila(431, 57, null, "Saghata", "সাঘাটা"),
                new Upazila(432, 57, null, "Gobindaganj", "গোবিন্দগঞ্জ"),
                new Upazila(433, 57, null, "Sundarganj", "সুন্দরগঞ্জ"),
                new Upazila(434, 57, null, "Phulchari", "ফুলছড়ি"),
                new Upazila(435, 58, null, "Thakurgaon Sadar", "ঠাকুরগাঁও সদর"),
                new Upazila(436, 58, null, "Pirganj", "পীরগঞ্জ"),
                new Upazila(437, 58, null, "Ranisankail", "রাণীশংকৈল"),
                new Upazila(438, 58, null, "Haripur", "হরিপুর"),
                new Upazila(439, 58, null, "Baliadangi", "বালিয়াডাঙ্গী"),
                new Upazila(440, 59, null, "Rangpur Sadar", "রংপুর সদর"),
                new Upazila(441, 59, null, "Gangachara", "গংগাচড়া"),
                new Upazila(442, 59, null, "Taragonj", "তারাগঞ্জ"),
                new Upazila(443, 59, null, "Badargonj", "বদরগঞ্জ"),
                new Upazila(444, 59, null, "Mithapukur", "মিঠাপুকুর"),
                new Upazila(445, 59, null, "Pirgonj", "পীরগঞ্জ"),
                new Upazila(446, 59, null, "Kaunia", "কাউনিয়া"),
                new Upazila(447, 59, null, "Pirgacha", "পীরগাছা"),
                new Upazila(448, 60, null, "Kurigram Sadar", "কুড়িগ্রাম সদর"),
                new Upazila(449, 60, null, "Nageshwari", "নাগেশ্বরী"),
                new Upazila(450, 60, null, "Bhurungamari", "ভুরুঙ্গামারী"),
                new Upazila(451, 60, null, "Phulbari", "ফুলবাড়ী"),
                new Upazila(452, 60, null, "Rajarhat", "রাজারহাট"),
                new Upazila(453, 60, null, "Ulipur", "উলিপুর"),
                new Upazila(454, 60, null, "Chilmari", "চিলমারী"),
                new Upazila(455, 60, null, "Rowmari", "রৌমারী"),
                new Upazila(456, 60, null, "Charrajibpur", "চর রাজিবপুর"),
                new Upazila(457, 61, null, "Sherpur Sadar", "শেরপুর সদর"),
                new Upazila(458, 61, null, "Nalitabari", "নালিতাবাড়ী"),
                new Upazila(459, 61, null, "Sreebordi", "শ্রীবরদী"),
                new Upazila(460, 61, null, "Nokla", "নকলা"),
                new Upazila(461, 61, null, "Jhenaigati", "ঝিনাইগাতী"),
                new Upazila(462, 62, null, "Fulbaria", "ফুলবাড়ীয়া"),
                new Upazila(463, 62, null, "Trishal", "ত্রিশাল"),
                new Upazila(464, 62, null, "Bhaluka", "ভালুকা"),
                new Upazila(465, 62, null, "Muktagacha", "মুক্তাগাছা"),
                new Upazila(466, 62, null, "Mymensingh Sadar", "ময়মনসিংহ সদর"),
                new Upazila(467, 62, null, "Dhobaura", "ধোবাউড়া"),
                new Upazila(468, 62, null, "Phulpur", "ফুলপুর"),
                new Upazila(469, 62, null, "Haluaghat", "হালুয়াঘাট"),
                new Upazila(470, 62, null, "Gouripur", "গৌরীপুর"),
                new Upazila(471, 62, null, "Gafargaon", "গফরগাঁও"),
                new Upazila(472, 62, null, "Iswarganj", "ঈশ্বরগঞ্জ"),
                new Upazila(473, 62, null, "Nandail", "নান্দাইল"),
                new Upazila(474, 62, null, "Tarakanda", "তারাকান্দা"),
                new Upazila(475, 63, null, "Jamalpur Sadar", "জামালপুর সদর"),
                new Upazila(476, 63, null, "Melandah", "মেলান্দহ"),
                new Upazila(477, 63, null, "Islampur", "ইসলামপুর"),
                new Upazila(478, 63, null, "Dewangonj", "দেওয়ানগঞ্জ"),
                new Upazila(479, 63, null, "Sarishabari", "সরিষাবাড়ী"),
                new Upazila(480, 63, null, "Madarganj", "মাদারগঞ্জ"),
                new Upazila(481, 63, null, "Bokshiganj", "বকশীগঞ্জ"),
                new Upazila(482, 64, null, "Barhatta", "বারহাট্টা"),
                new Upazila(483, 64, null, "Durgapur", "দুর্গাপুর"),
                new Upazila(484, 64, null, "Kendua", "কেন্দুয়া"),
                new Upazila(485, 64, null, "Atpara", "আটপাড়া"),
                new Upazila(486, 64, null, "Madan", "মদন"),
                new Upazila(487, 64, null, "Khaliajuri", "খালিয়াজুরী"),
                new Upazila(488, 64, null, "Kalmakanda", "কলমাকান্দা"),
                new Upazila(489, 64, null, "Mohongonj", "মোহনগঞ্জ"),
                new Upazila(490, 64, null, "Purbadhala", "পূর্বধলা"),
                new Upazila(491, 64, null, "Netrokona Sadar", "নেত্রকোণা সদর")
            };
        }
    }
}
